/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SeasonSummary } from '../../models/season-summary';

export interface GetCurrentUserSeason$Params {
  id: number;
  locationId?: number;
}

export function getCurrentUserSeason(http: HttpClient, rootUrl: string, params: GetCurrentUserSeason$Params, context?: HttpContext): Observable<StrictHttpResponse<SeasonSummary>> {
  const rb = new RequestBuilder(rootUrl, getCurrentUserSeason.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('locationId', params.locationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SeasonSummary>;
    })
  );
}

getCurrentUserSeason.PATH = '/api/v1/seasons/{id}';
