/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SeasonTopEntry } from '../../models/season-top-entry';

export interface ListCurrentUserSeasonTop$Params {
  id: number;
  n: 1 | 2 | 4 | 8 | 13 | 25 | 50 | 100;
  limit?: number;
  locationId?: number;
}

export function listCurrentUserSeasonTop(http: HttpClient, rootUrl: string, params: ListCurrentUserSeasonTop$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SeasonTopEntry>>> {
  const rb = new RequestBuilder(rootUrl, listCurrentUserSeasonTop.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('n', params.n, {});
    rb.query('limit', params.limit, {});
    rb.query('locationId', params.locationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SeasonTopEntry>>;
    })
  );
}

listCurrentUserSeasonTop.PATH = '/api/v1/seasons/{id}/top';
