/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActivityLap {
  datetimeStart?: string;
  duration?: string;
  lapNr?: number;
  movingAvgDuration?: string;
  rest?: boolean;
  sessionNr?: number;
  speedKph?: number;
}
