/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface AuthResponse {
  refreshToken?: string;
  token?: string;
  user?: User;
}
