/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChipDto {
  chipCode?: string;
  chipLabel?: string;
  createdAt?: string;
  id?: number;
  status?: string;
  userId?: number;
  validUntil?: string;
}
