/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequest {
  email: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  password: string;
  username: string;
}
