/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SeasonTopEntry {
  activityId?: number;
  chipId?: number;
  duration?: string;
  locationId?: number;
  n?: number;
  startTime?: string;
}
