/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  middleName?: string;
  username?: string;
}
