/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ActivityLap } from '../models/activity-lap';
import { ActivitySummary } from '../models/activity-summary';
import { getCurrentUserActivity } from '../fn/activities/get-current-user-activity';
import { GetCurrentUserActivity$Params } from '../fn/activities/get-current-user-activity';
import { listCurrentUserActivities } from '../fn/activities/list-current-user-activities';
import { ListCurrentUserActivities$Params } from '../fn/activities/list-current-user-activities';
import { listCurrentUserActivityLaps } from '../fn/activities/list-current-user-activity-laps';
import { ListCurrentUserActivityLaps$Params } from '../fn/activities/list-current-user-activity-laps';


/**
 * Current-user activity summaries
 */
@Injectable({ providedIn: 'root' })
export class ActivitiesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listCurrentUserActivities()` */
  static readonly ListCurrentUserActivitiesPath = '/api/v1/activities';

  /**
   * List current-user activities.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listCurrentUserActivities()` instead.
   *
   * This method doesn't expect any request body.
   */
  listCurrentUserActivities$Response(params?: ListCurrentUserActivities$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ActivitySummary>>> {
    const obs = listCurrentUserActivities(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List current-user activities.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listCurrentUserActivities$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listCurrentUserActivities(params?: ListCurrentUserActivities$Params, context?: HttpContext): Observable<Array<ActivitySummary>> {
    const resp = this.listCurrentUserActivities$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ActivitySummary>>): Array<ActivitySummary> => r.body)
    );
  }

  /** Path part for operation `getCurrentUserActivity()` */
  static readonly GetCurrentUserActivityPath = '/api/v1/activities/{id}';

  /**
   * Get one current-user activity.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCurrentUserActivity()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUserActivity$Response(params: GetCurrentUserActivity$Params, context?: HttpContext): Observable<StrictHttpResponse<ActivitySummary>> {
    const obs = getCurrentUserActivity(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get one current-user activity.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCurrentUserActivity$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUserActivity(params: GetCurrentUserActivity$Params, context?: HttpContext): Observable<ActivitySummary> {
    const resp = this.getCurrentUserActivity$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ActivitySummary>): ActivitySummary => r.body)
    );
  }

  /** Path part for operation `listCurrentUserActivityLaps()` */
  static readonly ListCurrentUserActivityLapsPath = '/api/v1/activities/{id}/laps';

  /**
   * List laps for a current-user activity.
   *
   * All laps across all sessions of the activity, ordered by datetimeStart then lapNr.
   * Includes sessionNr so the client can group by session.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listCurrentUserActivityLaps()` instead.
   *
   * This method doesn't expect any request body.
   */
  listCurrentUserActivityLaps$Response(params: ListCurrentUserActivityLaps$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ActivityLap>>> {
    const obs = listCurrentUserActivityLaps(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List laps for a current-user activity.
   *
   * All laps across all sessions of the activity, ordered by datetimeStart then lapNr.
   * Includes sessionNr so the client can group by session.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listCurrentUserActivityLaps$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listCurrentUserActivityLaps(params: ListCurrentUserActivityLaps$Params, context?: HttpContext): Observable<Array<ActivityLap>> {
    const resp = this.listCurrentUserActivityLaps$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ActivityLap>>): Array<ActivityLap> => r.body)
    );
  }

}
