/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ChipDto } from '../models/chip-dto';
import { getCurrentUserChips } from '../fn/chips/get-current-user-chips';
import { GetCurrentUserChips$Params } from '../fn/chips/get-current-user-chips';
import { linkChipToCurrentUser } from '../fn/chips/link-chip-to-current-user';
import { LinkChipToCurrentUser$Params } from '../fn/chips/link-chip-to-current-user';
import { unlinkChipFromCurrentUser } from '../fn/chips/unlink-chip-from-current-user';
import { UnlinkChipFromCurrentUser$Params } from '../fn/chips/unlink-chip-from-current-user';


/**
 * Link and list transponder chips for the current user
 */
@Injectable({ providedIn: 'root' })
export class ChipsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCurrentUserChips()` */
  static readonly GetCurrentUserChipsPath = '/api/v1/users/chips';

  /**
   * List chips linked to the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCurrentUserChips()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUserChips$Response(params?: GetCurrentUserChips$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChipDto>>> {
    const obs = getCurrentUserChips(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List chips linked to the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCurrentUserChips$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUserChips(params?: GetCurrentUserChips$Params, context?: HttpContext): Observable<Array<ChipDto>> {
    const resp = this.getCurrentUserChips$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ChipDto>>): Array<ChipDto> => r.body)
    );
  }

  /** Path part for operation `linkChipToCurrentUser()` */
  static readonly LinkChipToCurrentUserPath = '/api/v1/users/chips/{chipCode}';

  /**
   * Link a chip to the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `linkChipToCurrentUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  linkChipToCurrentUser$Response(params: LinkChipToCurrentUser$Params, context?: HttpContext): Observable<StrictHttpResponse<ChipDto>> {
    const obs = linkChipToCurrentUser(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Link a chip to the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `linkChipToCurrentUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  linkChipToCurrentUser(params: LinkChipToCurrentUser$Params, context?: HttpContext): Observable<ChipDto> {
    const resp = this.linkChipToCurrentUser$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ChipDto>): ChipDto => r.body)
    );
  }

  /** Path part for operation `unlinkChipFromCurrentUser()` */
  static readonly UnlinkChipFromCurrentUserPath = '/api/v1/users/chips/{chipCode}';

  /**
   * Unlink a chip from the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `unlinkChipFromCurrentUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  unlinkChipFromCurrentUser$Response(params: UnlinkChipFromCurrentUser$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = unlinkChipFromCurrentUser(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Unlink a chip from the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `unlinkChipFromCurrentUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  unlinkChipFromCurrentUser(params: UnlinkChipFromCurrentUser$Params, context?: HttpContext): Observable<void> {
    const resp = this.unlinkChipFromCurrentUser$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
