/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { importActivities } from '../fn/import/import-activities';
import { ImportActivities$Params } from '../fn/import/import-activities';


/**
 * Import practice activities from Speedhive
 */
@Injectable({ providedIn: 'root' })
export class ImportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `importActivities()` */
  static readonly ImportActivitiesPath = '/api/v1/import/activities/{locationId}';

  /**
   * Import Speedhive activities for a location.
   *
   * Defaults to the current calendar year and at most 500 rows.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `importActivities()` instead.
   *
   * This method doesn't expect any request body.
   */
  importActivities$Response(params: ImportActivities$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    const obs = importActivities(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Import Speedhive activities for a location.
   *
   * Defaults to the current calendar year and at most 500 rows.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `importActivities$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  importActivities(params: ImportActivities$Params, context?: HttpContext): Observable<string> {
    const resp = this.importActivities$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
