/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getCurrentUserSeason } from '../fn/seasons/get-current-user-season';
import { GetCurrentUserSeason$Params } from '../fn/seasons/get-current-user-season';
import { listCurrentUserSeasons } from '../fn/seasons/list-current-user-seasons';
import { ListCurrentUserSeasons$Params } from '../fn/seasons/list-current-user-seasons';
import { listCurrentUserSeasonTop } from '../fn/seasons/list-current-user-season-top';
import { ListCurrentUserSeasonTop$Params } from '../fn/seasons/list-current-user-season-top';
import { SeasonSummary } from '../models/season-summary';
import { SeasonTopEntry } from '../models/season-top-entry';


/**
 * Current-user season summaries and top-N lists
 */
@Injectable({ providedIn: 'root' })
export class SeasonsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listCurrentUserSeasons()` */
  static readonly ListCurrentUserSeasonsPath = '/api/v1/seasons';

  /**
   * List current-user seasons.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listCurrentUserSeasons()` instead.
   *
   * This method doesn't expect any request body.
   */
  listCurrentUserSeasons$Response(params?: ListCurrentUserSeasons$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SeasonSummary>>> {
    const obs = listCurrentUserSeasons(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List current-user seasons.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listCurrentUserSeasons$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listCurrentUserSeasons(params?: ListCurrentUserSeasons$Params, context?: HttpContext): Observable<Array<SeasonSummary>> {
    const resp = this.listCurrentUserSeasons$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<SeasonSummary>>): Array<SeasonSummary> => r.body)
    );
  }

  /** Path part for operation `getCurrentUserSeason()` */
  static readonly GetCurrentUserSeasonPath = '/api/v1/seasons/{id}';

  /**
   * Get one current-user season.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCurrentUserSeason()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUserSeason$Response(params: GetCurrentUserSeason$Params, context?: HttpContext): Observable<StrictHttpResponse<SeasonSummary>> {
    const obs = getCurrentUserSeason(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get one current-user season.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCurrentUserSeason$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUserSeason(params: GetCurrentUserSeason$Params, context?: HttpContext): Observable<SeasonSummary> {
    const resp = this.getCurrentUserSeason$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<SeasonSummary>): SeasonSummary => r.body)
    );
  }

  /** Path part for operation `listCurrentUserSeasonTop()` */
  static readonly ListCurrentUserSeasonTopPath = '/api/v1/seasons/{id}/top';

  /**
   * Top activities for a season by best-N duration.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listCurrentUserSeasonTop()` instead.
   *
   * This method doesn't expect any request body.
   */
  listCurrentUserSeasonTop$Response(params: ListCurrentUserSeasonTop$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SeasonTopEntry>>> {
    const obs = listCurrentUserSeasonTop(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Top activities for a season by best-N duration.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listCurrentUserSeasonTop$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listCurrentUserSeasonTop(params: ListCurrentUserSeasonTop$Params, context?: HttpContext): Observable<Array<SeasonTopEntry>> {
    const resp = this.listCurrentUserSeasonTop$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<SeasonTopEntry>>): Array<SeasonTopEntry> => r.body)
    );
  }

}
