/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { syncCurrentUser } from '../fn/sync/sync-current-user';
import { SyncCurrentUser$Params } from '../fn/sync/sync-current-user';


/**
 * Trigger activity sync for the current user
 */
@Injectable({ providedIn: 'root' })
export class SyncService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `syncCurrentUser()` */
  static readonly SyncCurrentUserPath = '/api/activity/sync';

  /**
   * Sync current-user activities.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `syncCurrentUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  syncCurrentUser$Response(params?: SyncCurrentUser$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = syncCurrentUser(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Sync current-user activities.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `syncCurrentUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  syncCurrentUser(params?: SyncCurrentUser$Params, context?: HttpContext): Observable<void> {
    const resp = this.syncCurrentUser$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
