/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ImportActivities$Params {
  locationId: number;

/**
 * Calendar year to import. Defaults to the current year.
 */
  year?: number;

/**
 * Maximum number of activities to import.
 */
  max?: number;
}

export function importActivities(http: HttpClient, rootUrl: string, params: ImportActivities$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, importActivities.PATH, 'post');
  if (params) {
    rb.path('locationId', params.locationId, {});
    rb.query('year', params.year, {});
    rb.query('max', params.max, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

importActivities.PATH = '/api/v1/import/activities/{locationId}';
