/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActivitySummary } from '../../models/activity-summary';

export interface GetCurrentUserActivity$Params {
  id: number;
}

export function getCurrentUserActivity(http: HttpClient, rootUrl: string, params: GetCurrentUserActivity$Params, context?: HttpContext): Observable<StrictHttpResponse<ActivitySummary>> {
  const rb = new RequestBuilder(rootUrl, getCurrentUserActivity.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ActivitySummary>;
    })
  );
}

getCurrentUserActivity.PATH = '/api/v1/activities/{id}';
