/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActivityLap } from '../../models/activity-lap';

export interface ListCurrentUserActivityLaps$Params {
  id: number;
}

export function listCurrentUserActivityLaps(http: HttpClient, rootUrl: string, params: ListCurrentUserActivityLaps$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ActivityLap>>> {
  const rb = new RequestBuilder(rootUrl, listCurrentUserActivityLaps.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ActivityLap>>;
    })
  );
}

listCurrentUserActivityLaps.PATH = '/api/v1/activities/{id}/laps';
